### ISSUE TITLE
Cannot delete Rest API becuase of existing basepath mapping

### ISSUE THREAD

**Issue by keviryan** [keviryan/reaver#1]
Traceback (most recent call last):
      File "reaver.py", line 50, in delete_apis
        restApiId=api_id
      File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
        return self._make_api_call(operation_name, kwargs)
      File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
        raise error_class(parsed_response, operation_name)
    botocore.errorfactory.BadRequestException: An error occurred (BadRequestException) when calling the DeleteRestApi operation: Deleting RestApi oztrumb09b failed. Please remove all base path mappings related to the RestApi in your domains: apigw.trankien.myinstance.com
     
    During handling of the above exception, another exception occurred:
     
    Traceback (most recent call last):
      File "reaver.py", line 119, in <module>
        main()
      File "reaver.py", line 116, in main
        delete_apis(get_apis(),delete_these)
      File "reaver.py", line 54, in delete_apis
        except apigw.exceptions.TooManyRequests:
      File "/usr/local/lib/python3.6/site-packages/botocore/errorfactory.py", line 53, in __getattr__
        self, name, ', '.join(exception_cls_names)))
    AttributeError: <botocore.errorfactory.APIGatewayExceptions object at 0x10693b7b8> object has no attribute 'TooManyRequests'. Valid exceptions are: BadRequestException, ConflictException, LimitExceededException, NotFoundException, ServiceUnavailableException, TooManyRequestsException, UnauthorizedException

**Comment by keviryan** [comment]
https://github.com/keviryan/reaver/commit/2219e5f2bd6049630eabddfb017e097c3db06a8d#diff-e35bdac9366bfa3f41ec69b7d62b5057
